### ISSUE TITLE
More Ais values for the node server

### ISSUE THREAD

**Issue by afischerdev** [SignalK/signalk-server-node#126]
I'd like to have some more values on ais messages.
But I think before I fork some clearing could be helpful.

It's a good idea to use ship specifications for ais ship messages.

But 
1. I found navigation.state as string and with a different meaning then in ais definition.
Should the ais state become an extra spec as integer - all clients with nmea input can handle that better than with a string value that must be converted. 

2. In the test logs for the java server I found the design.draft for the draught value. In the Signal K secification design.draft is a node point for some values. Should the draught move to e.g design.draft.maximum or should the definition type change to number and a unit added?

3. What about ais messages that do not represent a ship - e.g. base station or aid to navigation? Do they become an own specification group? And is it a better way to integrate all ais values into this group to have a clear definition - see above navigation state?

**Comment by sumps** [comment]
There are a few Issues in https://github.com/SignalK/specification that are applicable to this...

https://github.com/SignalK/specification/issues/74
https://github.com/SignalK/specification/issues/164
https://github.com/SignalK/specification/issues/171

It is the Specification that needs to be expanded/improved first.

**Comment by afischerdev** [comment]
Ok, let's try to bring them together.

MMSI -> mmsi (string)

Vessel - includes MOB, SART, EPIRB:
IMO number -> registrations.imo
Call sign -> communication.callsignvhf (callsignhf looks more amateur radio)
Vessel name -> name
Ship Type -> subtype (proposed integer)
Navigation Status -> navigation.status (proposed integer)
Dimension to Bow -> design.bowOffset (proposed integer)
Dimension to Stern -> design.sternOffset (proposed integer)
Dimension to Port -> design.portOffset (proposed integer)
Dimension To Starboard -> design.starboardOffset (proposed integer)
ETA month, ETA day, ETA hour, ETA minute -> navigation.destination.eta
Draught -> design.draft.maximum (prefered before minimum)
Destination -> navigation.destination.name (proposed)
Text -> notifications.text  (proposed)

Other object:
collect in a new group aisobject with
aircraft
aircraft.altitude
basestation
aidtonavigation
aidtonavigation.aidtype (integer)
aidtonavigation.name

For ais objects SoG, CoG, position - if needed - from vessel

I hope a small definition, just filled in what is coming from ais message, the interpretation leave up to the client.

**Comment by tkurki** [comment]
Hi!

As @sumps pointed out we already have a bunch of issues under signalk/specification that are about some of the stuff you pointed out. This issue is under `signalk-server-node`- technically none of your proposed changes will probably mean changes to `signalk-server-node`, but first changes to the Signal K specification (schema if you may) and then changes to https://github.com/SignalK/signalk-parser-nmea0183 and/or https://github.com/SignalK/n2k-signalk/. 

I am closing this issue, not because the points that you made are not valid, but because this is the wrong place to have this discussion and for example people watching the [specification](https://github.com/SignalK/specification) repo are not aware of it here.

So let's continue the discussion in the issues Paul pointed out.
