### ISSUE TITLE
feat: load new and updated plugins without full server reboot

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/signalk-server-node#528]
Ability to load new and updated plugins without having to reboot the server.
Maybe this could be done with something like `delete require.cache[require.resolve('some-plugin')]; require('some-plugin')`

**Comment by tkurki** [comment]
We already have the  problem of allowing plugins to add Express routes with no way to disable them when a plugin is disabled (because Express provides no public api for doing that).

I believe implementation would be complex and would not reach 100% coverage, so we would end up recommending restarting anyway for any mysterious problems.

See also #545.

Closing, as restarting while stupid is very easy and trouble free.
