### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by mauroc** [SignalK/signalk-server-node#54]
is there a simple way to run Signalk using SSL (as in https://localhost:3000/signalk/api/v1/vessels/   instead of http://localhost:3000 ....). Either with self-signed certs or CA-issued ones.

**Comment by tkurki** [comment]
Sorry about the late reply.

You can certainly use SSL. It was in master and if I recall correctly even default behavior, but since browsers would silently fail with self-signed certs it was removed to avoid confusion.

You can take a look at 9afb0e136887add3b3e6e5499cd654567bc4674c and resurrect that behavior. If you feel it is useful enough please try to come up with a PR where you can enable it with configuration.

If you need help let me know.

**Comment by tkurki** [comment]
Closing as there is no feedback.

**Comment by tkurki** [comment]
See #65

**Comment by tkurki** [comment]
Closed by #65
