### ISSUE TITLE
Develop create-signalk-plugin pkg for use with yarn create

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/signalk-server-node#543]
Running `yarn create signalk-plugin` would walk developer through a process to configure and install boilerplate code for creating a new plugin. Necessary tag added to keywords etc.

https://yarnpkg.com/blog/2017/05/12/introducing-yarn/

In the future the same `create-*` package will be supported by [npm init](https://t.co/E2U5Pw53u0).

**Comment by tkurki** [comment]
I think it would make more sense to include a demo & test plugin within the server and document how you can bootstrap a new plugin with it. This should be in Typescript so that we can better define the server-plugin API. 

I fear that a separate create-signalk-plugin would add more maintenance burden than it can provide value, as starting with a plugin is not overly complicated: grab one that is close to what you'd like to do and use the documentation, that is a lot better nowadays than it used to be.

A demo plugin that is compiled and exercised by CI has a much better chance at providing value to everybody, server and plugin developers included.
