### ISSUE TITLE
Use timestamp in GPS for server

### ISSUE THREAD

**Issue by jobarne** [SignalK/signalk-server-node#59]
It would be nice if there would be a setting (similar to the config.server.clock.source in the java server) so that the server uses the timestamps from the GPS (if available) rather than the server's own clock.

If one uses a Rapsberry Pi as a platform, it does not have an internal battery to keep the clock updated.

**Comment by fabdrol** [comment]
Note to self: implement using a separate `provider` that can be piped after any NMEA0183 source (e.g. TCP, UDP or (USB/)serial). Maybe another version that works with N2K as well (@tkurki)?

**Comment by tkurki** [comment]
You mean a PipedProvider element? Yeah, would work at the end of the pipe, where the data is in SK format.

The element could work as a latch, dropping all data on the floor until there is proper data in the system and failsafe system where it opens the connection after a fixed timeout, so you get other data if you forgot to turn your gps on. This way you should not get weird timestamp sequences in logs.

**Comment by fabdrol** [comment]
Can't we simply let it set system time if a valid timestamp is received? That way, if the connection ends or GPS is turned off, system time should be synced.

**Comment by tkurki** [comment]
What I meant was
- RPi starts, no system time available, starts node server
- the system-time-sync element receives all incoming data in Signal K providers, but does not pass them to the actual server, since there is no system time (assuming that this is a wanted functionality)
- upon receiving the first timestamp from gps it sets the system time & starts passing incoming data to the server

But this latching functionality is probably not needed. 

You might not want to set the system time with every gps timestamp, just once or once and then periodically.

Anyway, one could set up a pipe element that reads SK delta, sets the time from the appropriate message and passes all messages along to the server.

Example of running a shell command: https://github.com/SignalK/signalk-server-node/blob/master/providers/execute.js

Example of an almost no-operation pipe element: https://github.com/SignalK/signalk-server-node/blob/master/providers/from_json.js

@fabdrol does nmea0183-signalk-parser output datetime for gps messages? https://github.com/SignalK/specification/blob/45d93fb9c7984fa3ca64695088bc5b27825e3899/schemas/groups/navigation.json#L520

**Comment by fabdrol** [comment]
@tkurki maybe a bit extreme for most Use cases, but I can imagine that that would be useful to scientific or professional vessels where no time is a serious issue

I would say that, for most users, setting it once per session would be enough. The provider could simply set a variable to true once set, so it won't set (and just pass through data) after it's been set. That way it'll only (re)set time after each server restart

Regarding the parser: current version sets the timestamp value of each property to date and/or time if it receives that data from the NMEA sentence it's parsing. It assumes system date and/or time for missing values (so if time is passed but no date, it sets date to today).

This approach is straight forward and simple, but also naive. The new "lite" version that I still have to finish writing mappings for is more flexible; you could add a "transform" step that correctly parses the time based on the sentence specification. So, basically, WIP.

**Comment by tkurki** [comment]
Implemented as a plugin: https://github.com/tkurki/set-system-time
