### ISSUE TITLE
Ability to filter or select N2K data

### ISSUE THREAD

**Issue by jsholovitz** [SignalK/signalk-server-node#640]
I would like to request an ability to filter or select which incoming NMEA 200 data sources to use in SignalK. For example, on my network, there are multiple sources providing certain data types - like GPS data. I'd like to be able to select only one to be used in SK.

For example, I'd like to be able to select that a certain data type - or a certain PGN - should come only from i.e. canbus.127 and not canbus.128 when both are available. It would also be nice to have a checkbox for that PGN to allow it to use alternate sources when the selected primary source is not present?

It would also be nice in this feature if there was an ability to ignore certain PGN / source combinations - I have a use case where I have two B&G Triton displays on my network and, for some reason, they also send out Magnetic Variation PGNs. Most N2K devices simply ignore these and get their magnetic variation from the primary GPS device (which generally I have selected in their menus) however SK picks it up, translates it, and my GPS position jumps around in OpenCPN.

**Comment by tkurki** [comment]
This is the kind of functionality that I am not too keen to implement within the server core. Chasing each use case we may end up with a very complex UI that still is not flexible enough.

However there already exists a solution for this: the server's API includes a way for plugins to intercept incoming data before it is processed by the server: [DeltaInputHandler](https://github.com/SignalK/signalk-server-node/blob/master/SERVERPLUGINS.md#appregisterdeltainputhandler-delta-next--). This means that plugins can be used to implement what you want.

Furthermore we have a general purpose plugin, Node-RED, that you can use to implement the rules that you are after. You can use [signalk-input-handler](https://github.com/SignalK/node-red-embedded#signalk-input-handler) with a path to intercept for example navigation.speedOverGround, inspect the data and either ignore the input or pass it on to [signalk-input-handler-next](https://github.com/SignalK/node-red-embedded#signalk-input-handler-next) for processing.

*Note* that there seems to be a problem with $source handling in signalk-input-handler. Simply adding a path and a $source to ignore data from a source will not work until the issue is resolved.

If you need help with figuring out the Node-RED flows please add issues in https://github.com/SignalK/node-red-embedded or join Signal K Slack at http://slack-invite.signalk.org/, there is a separate channel for node-red related discussion.

**Comment by sbender9** [comment]
You can do this today even with the issue above. Use  signalk-input-handler and just enter the path, then connect that to a "switch" node.  In the switch node for path, choose `msg`, then enter `source.src`. Then for the conditions you can have something like '== 5' to only use position from N2K src 5.

**Comment by sbender9** [comment]
If you want to prefer a certain src unless it is not there, this node function can be used. In this example, it will prefer src 43, but if it has not seen that for 60 seconds, then it will use data from any src.

```
const timeout = 60
const prefered = '43'
let lastSeen = context.get('lastSeen')

if ( msg.source.src === prefered )
{
    node.send(msg)
    context.set('lastSeen', Date.now())
} else if ( !lastSeen ) {
    node.send(msg)
} else if ( Date.now() - lastSeen > (timeout *60)) {
    node.send(msg)
}
```

**Comment by sbender9** [comment]
Examples of the above

https://github.com/SignalK/node-red-embedded/blob/master/examples/filter-out-n2k-src.json

https://github.com/SignalK/node-red-embedded/blob/master/examples/preffered-n2k-src.json
