### ISSUE TITLE
Service Discovery

### ISSUE THREAD

**Issue by bdbcat** [SignalK/signalk-server-node#916]
I am building an sk/JSON client for OpenCPN.  Good progress so far.
I have the node.js server running on rPI, and have found that it serves JSON to a TCP socket on port 8375 by apparent default.  Subscription and data updates all work fine.

The problem is now with auto-discovery.
For service discovery using mDNS, I cannot determine the correct port to use.  When queried for "_signalk-http._tcp.local", the present version reports the correct ip, but the reported port is "3000".  The server will not respond to requests over a TCP socket  at port 3000.

What am I missing?
Dave

**Comment by tkurki** [comment]
_signalk-http._tcp is the http/ws service, that is technically tcp but not sk-delta-streaming-over-tcp. Try __signalk-tcp._tcp_ and let me know how that works for you.

This is what I referred to with my comment the other day: we have yet to canonize this service in the specification, even if the implementations are there. See also https://github.com/SignalK/specification/pull/559

**Comment by tkurki** [comment]
And the implementation and the spec addition not being in line is intentional, I am not sure what is the best name. _sk tcp over tcp_ seems a bit silly, so seeking input with the spec addition.

**Comment by bdbcat** [comment]
tkurki...
"_signalk-tcp._tcp.local" works fine, reports port=8375 as expected.
Wordsmithing:
The spec update maybe should somehow refer more explicitely the subscription model. "Streaming" implies, to me at least, that the data just automatically flows once a socket is opened.  But in the implementation so far, nothing at all happens until some subscription is registered.

Thanks
Dave

**Comment by sailoog** [comment]
After following the cruiserforum thread about this, I agree this is the best way. This change should have major implications in OpenPlotter, do you have any implementation calendar?

**Comment by tkurki** [comment]
Was this a question to Dave or me?

Can you elaborate on OP implications?

**Comment by sailoog** [comment]
to Dave.

One of the OpenPlotter goals is to make easier understand the data flow from your source to OpenCPN (or any other target like Dashboards, external devices...). Since currently OpenCPN only understands NMEA 0183, we have to guide users to the right plugins if they are not using NMEA 0183 sources and this is a little bit confusing for some of them. Finally we have just to watch the TCP localhost:10110 input is enabled in OpenCPN.

Having a SK input in OpenCPN means no plugins will be required and users should only worry about getting data in SK and we should only watch for an enabled SK input in OpenCPN.

**Comment by bdbcat** [comment]
We should see some OCPN code committed this weekend.
As you observe, many practical user cases can be served by having a simple sk/JSON channel into OCPN core.  And this is what I am building.  There are implications regarding the server, wherever it lives, and it's data providers.  But this can now be independent form OCPN core, at least.

**Comment by o-charts** [comment]
Agree. I can test it on Monday if you need. Thanks.

**Comment by sailoog** [comment]
Agree. I can test it on Monday if you need. Thanks.

**Comment by tkurki** [comment]
@bdbcat 

Upon rereading latest (1.3) SK Spec I discovered that we already hint at the service type `_signalk-tcp._tcp`, so I believe we should leave that as it is to be backwards compatible.

Something was nagging me about your earlier comment about subscriptions: in fact the Node server does not support subscriptions over TCP. I think it was left on the backlog waiting for adding the line termination (or lack of one) to the specification, that is yet to happen. I will start working on the subscription support shortly. The issue to track is #179.

Reviewing the specification additions in SignalK/specification#559 I think it makes much more sense to start the TCP connection in subscription policy `none`, otherwise the client may get a burst of data it doesn't want upon connection before issuing _unsubcribe all_. For you it means that you should open the connection and send subscription message for self  for all or some set of paths.

I am closing this issue, as the specification additions and tcp subscription support are better tracked via individual issues. Please continue there, if/when there's more stuff.
